---
title: "James Conigrave's resume"
author: James Conigrave
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    self_contained: true
    yml_toc: true
    css: ["resume","style-rules_publist.css"]
knit: pagedown::chrome_print
---

```{r data-load, message=FALSE, warning=FALSE, echo=FALSE, include = FALSE}
library(dplyr); library(ggplot2)

id = "m0d4TKcAAAAJ"
pubs = scholar::get_publications(id, flush = TRUE) %>%
  filter(journal != "ACU Research Bank") %>%
  mutate(author_last = gsub("^\\w{1,} *","",author)) %>% 
  arrange(desc(year), author_last)

pubs$author = scholar::get_complete_authors(id, pubs$pubid)

pubs = pubs %>% dplyr::mutate_if(is.factor, as.character)

pubs$journal = ifelse(nchar(pubs$journal) > 0, paste0("*",pubs$journal,"*"), pubs$journal)
pubs$number = ifelse(nchar(pubs$number) > 0, paste0("*",pubs$number,"*"), pubs$number)

pubs$cite_word = ifelse(pubs$cites == 1, "citation","citations")
pubs$cite_word = ifelse(pubs$cites == 0, "",pubs$cite_word)
pubs$cites = ifelse(pubs$cites == 0, "N/A", paste("---",pubs$cites))

pubs$author = pubs$author %>% 
  gsub("J Conigrave", "JH Conigrave",.) %>% 
  gsub("JH Conigrave","<u>JH Conigrave<\\/u>",.) %>% 
  gsub("KSK Lee","KSK Lee",.)

pre_prints = pubs[pubs$journal == "*PsyArXiv*",]
pubs =  pubs[pubs$journal != "*PsyArXiv*",]

# pattern = "### {title}
# 
# {journal}, {number} --- {cites} citations
# 
# N/A
# 
# {year}
# 
# {author}
# 
# "

pattern = "### {author} ({year}). {title}. {journal} {number}

{cites} {cite_word}

N/A

{year}


"

fix_grammar = function(x) gsub("(?<!\\.)\\.\\.(?!\\.)","\\.",x, perl = T) %>% gsub("\\?\\.","\\?",.)
# regex interpretation. Match two dots and replace with one, if there's not an extra dot before, or after the two (three dots is a row).

publications = glue::glue(pattern, .envir = as.environment(pubs)) %>% 
   fix_grammar
  
  
pre_prints = glue::glue(pattern, .envir = as.environment(pre_prints)) %>% 
   fix_grammar

total_citations = scholar::get_profile(id)$total_cites
 
 h_index = scholar::predict_h_index(id)[1,2]
# cit_plot = ggplot(citations, aes(year, cites)) +
#   geom_bar(stat= "identity") + theme_classic() +
#   labs(y = "Citations",
#        x = "") +
#   scale_y_continuous(labels = scales::number_format(accuracy = 1)) +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1))

CRAN_downloads = cranlogs::cran_downloads(c("corx","Conigrave"), from = "2015-01-01", to = lubridate::today()) %>% 
  group_by(package) %>% 
  summarise(dls = sum(count))

```


Main
================================================================================

James Conigrave, PhD {#title}
--------------------------------------------------------------------------------

Published articles {data-icon=file}
--------------------------------------------------------------------------------

```{r results = "asis", echo = FALSE, message = FALSE }

publications

```

Pre-prints {data-icon=file}
--------------------------------------------------------------------------------

```{r results = "asis", echo = FALSE, message = FALSE }

pre_prints

```

