name: Daily Run of conig::resume

on:
  schedule:
    - cron: '0 0 * * *'  # Trigger at midnight
  workflow_dispatch:     # Add manual dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.SECRETPAT }}  # Add this line
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup R Environment
      uses: r-lib/actions/setup-r@v2

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install system dependencies (Ubuntu)
      run: sudo apt-get install -y libcurl4-openssl-dev

    - name: Install curl
      run: |
        Rscript -e "install.packages(c('curl'))"

    - name: Install pkgdeps
      run: |
        Rscript -e "install.packages(c('pkgdepends', 'pkgcache'))"
        
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('scholar', 'cranlogs', 'rcrossref', 'revtools', 'pkgconfig', 'remotes'))"
      
    - name: Install the conig package
      run: |
        Rscript -e "remotes::install_github('conig/jamesconigrave')"

    - name: Create necessary directories
      run: mkdir -p /home/runner/work/_temp/Library/conig//to_github/resume/docs
      
    - name: Run conig::resume
      run: |
        Rscript -e 'conig::update_resume(path = "docs/index.html")'

        
