name: Daily Run of conig::resume

on:
  schedule:
    - cron: '0 0 * * *'  # Trigger at midnight
  workflow_dispatch:     # Add manual dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.SECRETPAT }}  # Add this line
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup R Environment
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('scholar', 'cranlogs', 'rcrossref', 'revtools', 'pak', 'pkgdepends', 'pkgconfig'))"
      
    - name: Install the conig package
      run: |
        Rscript -e "pak::pkg_install('conig/jamesconigrave')"

    - name: Run conig::resume
      run: |
        Rscript -e 'conig::resume(path = "docs/index.html")'

        
